all:aaa bbb ccc signal_handler
aaa:aaa.c
	gcc -o aaa aaa.c
bbb:bbb.c
	gcc -o bbb bbb.c
ccc:ccc.c
	gcc -o ccc ccc.c
signal_handler:signal_handler.c
	gcc -o signal_handler signal_handler.c

clean:
	rm -f aaa bbb ccc signal_handler
